name: CI-MLflow-Training-and-Docker

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  train-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install "mlflow<3" pandas scikit-learn joblib

      # =========================
      # 1️⃣ TRAIN MODEL (MLflow)
      # =========================
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager local

      # =========================
      # 2️⃣ LOGIN DOCKER HUB
      # =========================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # =========================
      # 3️⃣ BUILD DOCKER IMAGE
      # =========================
      - name: Build Docker image using MLflow
        run: |
          RUN_ID=$(ls mlruns/0 | tail -n 1)
          mlflow models build-docker \
            --model-uri runs:/0/$RUN_ID/model \
            --name docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gizibalita-logreg

      # =========================
      # 4️⃣ PUSH DOCKER IMAGE
      # =========================
      - name: Push Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gizibalita-logreg
