name: CI-MLflow-Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  train-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    # ==============================
    # 1. Checkout Repository
    # ==============================
    - name: Checkout repository
      uses: actions/checkout@v4

    # ==============================
    # 2. Setup Python
    # ==============================
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # ==============================
    # 3. Install dependencies
    # ==============================
    - name: Install MLflow & tools
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn joblib seaborn matplotlib

    # ==============================
    # 4. Run MLflow Project (Training)
    # ==============================
    - name: Run MLflow Project
      run: |
        mlflow run MLProject

    # ==============================
    # 5. Upload artifacts to GitHub
    # ==============================
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: |
          MLProject/model.joblib

    # ==============================
    # 6. Login to Docker Hub
    # ==============================
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ==============================
    # 7. Build Docker Image with MLflow
    # ==============================
    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          -m MLProject \
          -n saabrimr/gizibalita-logreg:latest

    # ==============================
    # 8. Push Docker Image
    # ==============================
    - name: Push Docker Image
      run: |
        docker push saabrimr/gizibalita-logreg:latest
